version: '3.8'

services:
  # 1. Database Service
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: pharma_db
      MYSQL_ROOT_PASSWORD: password_super_rahasia
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Opsional: taruh file backup.sql di folder ./init-db agar otomatis ter-import saat pertama kali jalan
      - ./init-db:/docker-entrypoint-initdb.d 

  # 2. Backend Service (Python + Prophet)
  backend:
    build: ./backend
    container_name: python_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:password_super_rahasia@db:3306/pharma_db
    depends_on:
      - db

  # 3. Frontend Service (Nuxt)
  frontend:
    build: ./frontend
    container_name: nuxt_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  mysql_data: